fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

carcel_user:
    resource: '@CarcelUserBundle/Resources/config/routing.yml'
    prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# redirecting the root
root:
    path: /
    defaults:
        _controller: 'FrameworkBundle:Redirect:urlRedirect'
        path: /
        permanent: true
