services:
    carcel_user.factory._user_form:
        class: Carcel\Bundle\UserBundle\Form\Factory\UserFormFactory
        arguments:
            - '@form.factory'
            - '@router'
            - '@translator'
