carcel_user_admin:
    path: /admin
    defaults: { _controller: CarcelUserBundle:User:index }

carcel_user_admin_show:
    path: /admin/{id}/show
    defaults: { _controller: CarcelUserBundle:User:showProfile }

carcel_user_admin_edit:
    path: /admin/{id}/edit
    defaults: { _controller: CarcelUserBundle:User:editProfile }

carcel_user_admin_update:
    path: /admin/{id}/update
    defaults: { _controller: CarcelUserBundle:User:updateProfile }
    methods:  [POST, PUT]

carcel_user_admin_set_role:
    path: /admin/{id}/role
    defaults: { _controller: CarcelUserBundle:User:setRole }
    methods:  [GET, POST, PUT]

carcel_user_admin_remove:
    path: /admin/{id}/delete
    defaults: { _controller: CarcelUserBundle:User:removeUser }
    methods:  [POST, DELETE]
