services:
    carcel_user.handler.logout_success_handler:
        class: Carcel\Bundle\UserBundle\Handler\LogoutSuccessHandler
        arguments:
            - '@carcel_user.factory.redirect_response'
        tags:
            - { name: 'monolog_logger', channel: 'security' }

    carcel_user.handler.user_status:
        class: Carcel\Bundle\UserBundle\Handler\UserStatusHandler
        arguments:
            - '@event_dispatcher'
            - '@doctrine.orm.entity_manager'
