fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Carcel\Bundle\UserBundle\Entity\User
    from_email:
        address: '%mailer_user%'
        sender_name: '%mailer_user%'
    registration:
        confirmation:
            enabled: true

framework:
    assets: ~
    csrf_protection: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    templating:
        engines: ['twig']
