fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

carcel_user:
    resource: "@CarcelUserBundle/Resources/config/routing.yml"
    prefix: /

root:
    path: /
    defaults:
        _controller: 'FrameworkBundle:Redirect:urlRedirect'
        path: /
        permanent: true
